[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "targeted_marketing_model"
version = "0.0.1"
description = "Predicting customer response to marketing campaigns using demographic and behavioral data."
authors = [
  { name = "Nathan Yang" },
]

readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["targeted_marketing_model"]
include = ["pyproject.toml", "targeted_marketing_model/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["targeted_marketing_model"]
force-sort-within-sections = true

